name: cryptotrack
description: Simple cryptocurrency application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^1.1.1
  path_provider: ^0.5.0+1
  cupertino_icons: ^0.1.2
  dio: ^2.1.3
  rxdart: ^0.22.0
  flutter_cache_manager: ^0.3.2
  flutter_launcher_icons: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/icons/btc.png"
  image_path_ios: "assets/images/icons/btc.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/